development:
  adapter: postgresql
  encoding: unicode
  database: pg_development
  pool: 5
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: pg_test
  pool: 5
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: pg_production
  pool: 5
  username: postgres
  password: 
